# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 14:16
from __future__ import unicode_literals

import cms.apps.media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20170407_1442'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.Destinations')),
                ('image', cms.apps.media.models.ImageRefField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.File')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'destination', 'verbose_name_plural': 'destinations'},
        ),
        migrations.AddField(
            model_name='destination',
            name='card_image',
            field=cms.apps.media.models.ImageRefField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.File', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='destination',
            name='card_text',
            field=models.TextField(default=0, max_length=140, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='destination',
            name='card_title',
            field=models.CharField(default=0, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='people_count',
            field=models.CharField(default=0, help_text='12-20, 4-6, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='related_facilities',
            field=models.ManyToManyField(blank=True, help_text='By default it will choose 3 random facilities to show. If you would like to ensure certain facilities always show you can choose them here.', related_name='_destination_related_facilities_+', to='destinations.Destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='room_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='features',
            field=models.ManyToManyField(related_name='_destination_features_+', to='destinations.Feature'),
        ),
        migrations.AddField(
            model_name='destination',
            name='key_features',
            field=models.ManyToManyField(help_text='These are the features that will appear in the header', to='destinations.Feature'),
        ),
    ]
