# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 14:32
from __future__ import unicode_literals

import cms.apps.media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20170407_1442'),
        ('destinations', '0002_auto_20171022_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='card_title',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='people_count',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='related_facilities',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='hero_kicker',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='hero_link_page',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='hero_link_text',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='hero_link_url',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='hero_text',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='destination',
            name='continent',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='flight_price',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='hotel_price',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=cms.apps.media.models.ImageRefField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.File', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='weather',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_image',
            field=cms.apps.media.models.ImageRefField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.File', verbose_name='Image'),
        ),
    ]
