# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_destination_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='card_text',
        ),
    ]
