# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_auto_20171022_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='featured',
        ),
    ]
