# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_remove_destination_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationimage',
            old_name='facility',
            new_name='destination',
        ),
    ]
