# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_auto_20171026_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationlanding',
            name='page',
        ),
        migrations.DeleteModel(
            name='DestinationLanding',
        ),
    ]
