# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:12
from __future__ import unicode_literals

import cms.apps.media.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20170407_1442'),
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='image',
            field=cms.apps.media.models.ImageRefField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.File', verbose_name='Image'),
        ),
    ]
